// <auto-generated />
namespace Edreamer.Framework.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Framework1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Framework1));
        
        string IMigrationMetadata.Id
        {
            get { return "201410181832413_Framework1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
