// <auto-generated />
namespace Rahnemun.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Rahnemun2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Rahnemun2));
        
        string IMigrationMetadata.Id
        {
            get { return "201410280922225_Rahnemun2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
