// <auto-generated />
namespace Rahnemun.Database.RahnemunMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Rahnemun25 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Rahnemun25));
        
        string IMigrationMetadata.Id
        {
            get { return "201511281852131_Rahnemun25"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
